### ISSUE TITLE
support testing of optional / mandatory parameters

### ISSUE THREAD

**Issue by petervandoros** [lonelyplanet/vigia#14]
Vigia should run two context when using the APIB blueprint adaptor. First, it should query the server using both optional and required params. In the second one, vigia should only use mandatory parameteres

It would be nice for vigia to provide this functionality when required.

**Comment by nogates** [comment]
I've added a new context to the adapter that configures the client only with the parameters marked as required.  :point_right:  #15

For now, this feature is enabled by default and there is not an easy way to configure it :(
